web/rx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user_auth.urls')),
    path('', include('rx_core.urls')),
]

web/rx_core/urls.py
from django.urls import path
from . import views

app_name = 'rx_core'

urlpatterns = [
	path('', views.index, name='index'),
	path('welcome/', views.index, name='welcome'),
	path('patients/', views.patient_portal, name='patient_portal'),
	path('patients/new/', views.PatientIntake.as_view(), name='patient_intake'),
	path('patients/thanks/', views.patient_confirmation, name='patient_confirmation'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('waiting-room/', views.WaitingRoomView.as_view(), name='waiting_room'),
	path('waiting-room/patient/<int:pk>', views.PatientDetailView.as_view(), name='patient_detail'),
	path('checked-patients/', views.CompletedRoomView.as_view(), name='checked_patients'),
]

web/user_auth/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('', include('django.contrib.auth.urls'))
]

web/rx_core/models.py
from django.db import models

import random #placeholder for CRN score
from django.utils import timezone

# Create your models here.

class Patient(models.Model):
    first_name = models.CharField(max_length=200)
    # middle_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    # Financial Factors
    INCOME = (
        (1, '<$15k'),
        (2, '$15k-$24.9k'),
        (3, '$25k-$34.9k'),
        (4, '$35k-$49.9k'),
        (5, '$50k or more'),
    )
    household_income = models.PositiveSmallIntegerField(choices=INCOME)

    BOOLEAN = ((1, 'Yes'), (0, 'No'))
    health_insurance = models.PositiveSmallIntegerField(choices=BOOLEAN)

    # Demographic Factors
    AGE = ((4, '<55'),(3, '55-64'),(2, '65-75'),(1, '75+'),)
    age = models.PositiveSmallIntegerField(choices=AGE)

    SEX = ((1, 'Female'),(2, 'Male'),(1, 'Other'),)
    sex = models.PositiveSmallIntegerField(choices=SEX)

    RACE = (
        (5, 'Non-Hispanic White'),
        (2, 'Non-Hispanic Black'),
        (1, 'Hispanic'),
        (4, 'Asian/Pacific Islander'),
        (3, 'Other'),
    )
    race = models.PositiveSmallIntegerField(choices=RACE, verbose_name="Race/Ethnicity")

    MARITAL = (
        (1, 'Living Alone'),
        (2, 'Married or Living with SO'),
    )
    marital_status = models.PositiveSmallIntegerField(choices=MARITAL)

    # Socioeconomic Factors
    EDUCATION = (
        (1, '<High School'),
        (1, 'Some High School'),
        (2, 'High School Grad or GED'),
        (2, 'Some College'),
        (3, 'College or More'),
    )
    education_level = models.PositiveSmallIntegerField(choices=EDUCATION)

    EMPLOYMENT = (
        (3, 'Employed/Self-employed'),
        (1, 'Not employed'),
        (4, 'Retired'),
        (2, 'Not in the workforce'),
    )
    employment_status = models.PositiveSmallIntegerField(choices=EMPLOYMENT)

    # Lifestyle Factors
    BOOLEAN = ((1, 'Yes'), (0, 'No'))
    physical_activity = models.PositiveSmallIntegerField(choices=BOOLEAN)
    alcohol_drinking = models.PositiveSmallIntegerField(choices=BOOLEAN)
    smoking_activity = models.PositiveSmallIntegerField(choices=BOOLEAN)
    weight = models.IntegerField(verbose_name="Weight (kg)")
    height = models.IntegerField(verbose_name="Height (m)")

    # Health Factors
    HEALTH_STATUS = ((4, 'Excellent'),(3, 'Good'),(2, 'Fair'),(1, 'Poor'),)
    general_health_status = models.PositiveSmallIntegerField(choices=HEALTH_STATUS)
    comorbidity = models.PositiveSmallIntegerField(choices=BOOLEAN, verbose_name="Other Health Conditions (Heart Attack, CHD, Stroke)")
    disability = models.PositiveSmallIntegerField(choices=BOOLEAN)

    other_info = models.TextField(default="")
    arrival_time = models.DateTimeField(default=timezone.now)
    checked = models.BooleanField(default=False)

    # Result returned after survey
    crn_score = models.IntegerField(default=50)

    def check_patient(self):
        self.checked = False
        return self.checked

    def body_mass_index(self):
        return (self.weight)/(self.height**2)

    def get_crn_score(self):
        """Calculated CRN likelihood score out of 100"""
        # self.crn_score = random.randrange(100)
        sum = (self.household_income + self.health_insurance + self.age +
              self.sex + self.race + self.marital_status + self.education_level +
              self.employment_status + self.physical_activity +
              self.alcohol_drinking + self.smoking_activity +
              self.general_health_status + self.comorbidity + self.disability)
        self.crn_score = (1-(sum/40)) * 100
        return self.crn_score

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

web/rx_core/forms.py
from django import forms
from .models import Patient

class PatientIntakeForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ('crn_score', 'checked',)

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'other_info': forms.Textarea(attrs={'class': 'form-control'}),
            }

web/rx_core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, DetailView
from django.urls import reverse_lazy

from django.utils import timezone

from .models import Patient
from .forms import PatientIntakeForm

def index(request):
    return render(request, 'rx_core/index.html')

def patient_portal(request):
    return render(request, 'rx_core/patient_portal.html')

class PatientIntake(CreateView):
    template_name = 'rx_core/patient_form.html'
    form_class = PatientIntakeForm
    success_url = reverse_lazy('rx_core:patient_confirmation')

    def get_initial(self, *args, **kwargs):
        initial = super(PatientIntake, self).get_initial(**kwargs)
        # initial['name'] = 'My Goal'
        return initial


def patient_confirmation(request):
    return render(request, 'rx_core/patient_confirmation.html')


# @login_required
def dashboard(request):
    return render(request, 'rx_core/dashboard.html')

# @login_required
class WaitingRoomView(ListView):
    template_name = 'rx_core/waiting_room.html'
    context_object_name = 'patient_list'

    def get_queryset(self):
        return Patient.objects.filter(checked=False)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['now'] = timezone.now()
    #     return context

class CompletedRoomView(ListView):
    template_name = 'rx_core/completed_room.html'
    context_object_name = 'patient_list'

    def get_queryset(self):
        return Patient.objects.filter(checked=True)

class PatientDetailView(DetailView):
    model = Patient

web/user_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return reverse_lazy('rx_core:dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

web/rx_core/templates/rx_core/app_base.html
{% extends 'rx_core/base.html' %}
{% load static %}

{%block extrahead %}
<!-- Custom styles for this template -->
<link href="{% static 'rx_core/css/simple-sidebar.css'%}" rel="stylesheet">
{%endblock %}


{%block content %}
  <div class="d-flex" id="wrapper">

    {% include "rx_core/sidebar.html" %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include "rx_core/navbar.html" %}

      <div class="container-fluid">
        <div class="row py-4 px-2">
          <div class="col-lg-10 col-sm-8">
            {%block page_title %}
              <h1>Default Page</h1>
            {% endblock %}
          </div>
          <div class="col-lg-2 col-sm-4 ml-auto">
            {%block info %}
            {% endblock %}
          </div>
        </div>

        {%block navtabs %}
        <hr/>
        {% endblock %}

        <div class="row p-2 py-4">
          {%block page %}
          <p>Default Page Content</p>
          {% endblock %}
        </div>
      </div>

    </div>
    <!-- /#page-content-wrapper -->
  </div>
{% endblock %}


{%block extrascripts %}
<!-- Menu Toggle Script -->
<script>
  $("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
  });
</script>
{%endblock %}

web/rx_core/templates/rx_core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Aecera - Your Healthcare Provider</title>
    <meta content="Get your lost-cost prescriptions here" name="description">
    <meta content="prescription, pharmary, prices" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'rx_core/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'rx_core/vendor/boxicons/css/boxicons.min.css'%}" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'rx_core/css/simple-sidebar.css'%}" rel="stylesheet">

    {%block extrahead %}
    {%endblock %}
  </head>

  <body>
      {%block header %}
      {% endblock %}

      {%block content %}
      <div class="container-fluid">
        <h1 class="mt-4">Default content</h1>
      </div>
      {% endblock %}

    <!-- Vendor JS Files -->
    <script src="{% static 'rx_core/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'rx_core/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'rx_core/vendor/jquery.easing/jquery.easing.min.js'%}"></script>

    {%block extrascripts %}
    {%endblock %}

    <!-- ======= Footer ======= -->
    <footer id="footer">
      <div class="container">
        <div class="copyright">
          &copy; Copyright 2020 <strong><span>Jennifer Long & Ishaan Dey</span></strong>. All Rights Reserved
        </div>
      </div>
    </footer><!-- End #footer -->

  </body>

</html>

web/rx_core/templates/rx_core/checked_out.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>Patient Log</h1>
{% endblock %}

{%block navtabs %}
<nav class="w-100">
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-current-tab"
       href="{% url 'rx_core:waiting_room' %}" role="tab">
       Waiting Patients</a>
    <a class="nav-item nav-link" id="nav-completed-tab"
       href="{% url 'rx_core:waiting_room' %}" role="tab">
       Checked Patients</a>
  </div>
</nav>
{% endblock %}

{%block page %}
<div class="card w-100">
  <div class="card-body">
    <p>No patients have checked out.</p>
  </div>
</div>
{% endblock %}

web/rx_core/templates/rx_core/completed_room.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>Waiting Room</h1>
{% endblock %}

{%block navtabs %}
<nav class="w-100">
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-current-tab"
       href="{% url 'rx_core:waiting_room' %}" role="tab">
       Waiting Patients</a>
    <a class="nav-item nav-link" id="nav-completed-tab"
       href="{% url 'rx_core:checked_patients' %}" role="tab">
       Checked Patients</a>
  </div>
</nav>
{% endblock %}

{%block page %}
    {% if patient_list %}
      {% for patient in patient_list %}
      <div class="col-lg-4 col-sm-6">
        <div class="card border-info mb-3">
          <div class="card-header">Arrived {{ patient.arrival_time }}</div>
          <div class="card-body text-info">
            <a href="{% url 'rx_core:patient_detail' patient.id %}">
              <h5 class="card-title">{{ patient }}</h5>
            </a>
            <p class="card-text">
              Age {{ patient.get_age_display }} {{ patient.get_sex_display }}<br/>
              BMI: {{ patient.body_mass_index }}
            </p>
          </div>
          <div class="card-footer text-muted">
            <div class="progress">
              <div class="progress-bar bg-warning" role="progressbar" style="width: {{ patient.get_crn_score }}%"
                   aria-valuenow="{{ patient.crn_score }}" aria-valuemin="0" aria-valuemax="100">
                {{ patient.crn_score }}
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    {% else %}
    <div class="col">
      <div class="card">
        <div class="card-body">
          <p>No patients yet!
          </p>
        </div>
      </div>
    </div>
    {% endif %}
{% endblock %}

web/rx_core/templates/rx_core/dashboard.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>Dashboard</h1>
{% endblock %}

{%block page %}
<div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2">
  <div class="row text-center">

    <div class="col">
      <div class="card text-white bg-danger h-100">
        <div class="card-header">
          <h5>I'm a Patient</h5>
        </div>
        <div class="card-body">
          <p class="card-text">
            Just arrived? Complete the patient intake form
          </p>
          <a href="{% url 'rx_core:patient_portal' %}" class="btn btn-light btn-block">Go there</a>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="card text-white bg-info h-100">
        <div class="card-header">
          <h5>I'm a Doctor</h5>
        </div>
        <div class="card-body">
          <p class="card-text">
            Examine the patients in your waiting room
          </p>
          <a href="{% url 'rx_core:waiting_room' %}" class="btn btn-light btn-block">Go there</a>
        </div>
      </div>
    </div>

  </div>
</div>
{% endblock %}

web/rx_core/templates/rx_core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Aecera</a>
  <button class="navbar-toggler" type="button" id="menu-toggle">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>

web/rx_core/templates/rx_core/patient_confirmation.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>Patient Portal</h1>
{% endblock %}

{%block page %}
<div class="col-lg-6 offset-lg-3">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Intake Form Submitted</h5>
      <p class="card-text">Thank you for checking in. A physician will be with you shortly.</p>
      <a href="{% url 'rx_core:patient_portal' %}" class="btn btn-primary">Return to main</a>
    </div>
  </div>
</div>
{% endblock %}

web/rx_core/templates/rx_core/patient_detail.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>Patient Detail</h1>
  <a href="{% url 'rx_core:waiting_room' %}" class="btn btn-secondary">Back to waiting room</a>
{% endblock %}

{%block info %}
<h5>Patient Checked: {{ patient.check_patient }}</h5>
<button type="button" class="btn btn-success btn-block">
  Mark as Checked
</button>
{% endblock %}

{%block page %}
<div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2">
  <h4>{{ patient }}</h4>
  <p>Arrived {{ patient.arrival_time }}</p>
  <br/>

  <div class="card">
    <div class="card-header">
      <h5>Financial Factors</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-4">
          <h6>Household Income</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-danger w-75" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_household_income_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Health Insurance</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-danger w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_health_insurance_display }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br/>

  <div class="card">
    <div class="card-header">
      <h5>Demographic Factors</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-4">
          <h6>Age</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-warning w-25" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_age_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Sex</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-warning w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_sex_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Race/Ethnicity</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-warning w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_race_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Marital Status</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress justify-content-center">
              {{ patient.get_marital_status_display }}
          </div>
        </div>
      </div>
    </div>
  </div>
  <br/>

  <div class="card">
    <div class="card-header">
      <h5>Socioeconomic Factors</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-4">
          <h6>Education Level</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-success w-75" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_education_level_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Employment Status</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress justify-content-center">
              {{ patient.get_employment_status_display }}
          </div>
        </div>
      </div>
    </div>
  </div>
  <br/>

  <div class="card">
    <div class="card-header">
      <h5>Health Factors</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-4">
          <h6>General Health Status</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-info w-75" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_general_health_status_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Comorbidity</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-info w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
               {{ patient.get_comorbidity_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Disability</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-info w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
               {{ patient.get_disability_display }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br/>

  <div class="card">
    <div class="card-header">
      <h5>Lifestyle Factors</h5>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-sm-4">
          <h6>Physical Activity</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-primary w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_physical_activity_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Alcohol Drinking</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress justify-content-center">
              {{ patient.get_alcohol_drinking_display }}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Smoking Activity</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-primary w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.get_smoking_activity_display }}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <h6>Body Mass Index (BMI)</h6>
        </div>
        <div class="col-sm-8">
          <div class="progress">
            <div class="progress-bar bg-primary w-100" role="progressbar"
                 aria-valuemin="0" aria-valuemax="5">
              {{ patient.body_mass_index }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

{% endblock %}

web/rx_core/templates/rx_core/patient_form.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>New Patient Form</h1>
{% endblock %}

{%block page %}
<div class="col-lg-8 offset-lg-2">
  <form method="post">{% csrf_token %}
      <h4>Patient Information</h4>
      <br/>
      <div class="non-field-errors">
          {% for err in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              {{ err }}
            </div>
          {% endfor %}
        </div>

        {% for field in form %}
          <div class="form-group">
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-4">
                    {{ field.label_tag }}
                  </div>
                  <div class="col-sm-8">
                    {{ field }}
                  </div>
                </div>
              </div>
              {% for err in field.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ err }}
                </div>
              {% endfor %}

          </div>
        {% endfor %}
      <hr/>
      <button type="submit" value="Save" class="btn btn-primary">
        Submit
      </button>
  </form>
</div>
{% endblock %}

web/rx_core/templates/rx_core/patient_portal.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>Patient Portal</h1>
{% endblock %}

{%block page %}
<div class="col-lg-6 offset-lg-3">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Intake form</h5>
      <p class="card-text">
        Please complete the intake form while you wait for your appointment.
        This will take approximately 3-5 minutes of your time.
      </p>
      <a href="{% url 'rx_core:patient_intake' %}" class="btn btn-primary">Begin form</a>
    </div>
  </div>
</div>
{% endblock %}

web/rx_core/templates/rx_core/sidebar.html
<!-- Sidebar -->
<div class="bg-light border-secondary border-right" id="sidebar-wrapper">
  <div class="sidebar-heading">
    My RX Predictor
  </div>
  <div class="list-group list-group-flush">
    <a href="{% url 'rx_core:dashboard' %}"
       class="list-group-item list-group-item-action bg-light">
       <i class="fa fa-th-large fa-fw"></i>&nbsp; Dashboard
    </a>
    <a href="{% url 'rx_core:waiting_room' %}"
       class="list-group-item list-group-item-action bg-light">
      <i class="fa fa-pencil-square-o fa-fw"></i>&nbsp; Waiting Room
    </a>
    <a href="{% url 'rx_core:patient_portal' %}"
       class="list-group-item list-group-item-action bg-light">
      <i class="fa fa-check-square-o fa-fw"></i>&nbsp; Patient Portal
    </a>
  </div>
</div>
<!-- /#sidebar-wrapper -->

web/rx_core/templates/rx_core/waiting_room.html
{% extends 'rx_core/app_base.html' %}
{% load static %}

{%block page_title %}
  <h1>Waiting Room</h1>
{% endblock %}

{%block navtabs %}
<nav class="w-100">
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-current-tab"
       href="{% url 'rx_core:waiting_room' %}" role="tab">
       Waiting Patients</a>
    <a class="nav-item nav-link" id="nav-completed-tab"
       href="{% url 'rx_core:waiting_room' %}" role="tab">
       Checked Patients</a>
  </div>
</nav>
{% endblock %}

{%block page %}
    {% if patient_list %}
      {% for patient in patient_list %}
      <div class="col-lg-4 col-sm-6">
        <div class="card border-info mb-3">
          <div class="card-header">Arrived {{ now }}</div>
          <div class="card-body text-info">
            <a href="{% url 'rx_core:patient_detail' patient.id %}">
              <h5 class="card-title">{{ patient }}</h5>
            </a>
            <p class="card-text">
              Age {{ patient.get_age_display }} {{ patient.get_sex_display }}<br/>
              BMI: {{ patient.body_mass_index }}
            </p>
          </div>
          <div class="card-footer text-muted">
            <div class="progress">
              <div class="progress-bar bg-warning" role="progressbar" style="width: {{ patient.get_crn_score }}%"
                   aria-valuenow="{{ patient.crn_score }}" aria-valuemin="0" aria-valuemax="100">
                {{ patient.crn_score }}
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    {% else %}
    <div class="col">
      <div class="card">
        <div class="card-body">
          <p>No patients yet!
          </p>
        </div>
      </div>
    </div>
    {% endif %}
{% endblock %}